"""
Pydantic models for Ontology Change Proposals.
Based on OSS Specification v1.0.0
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum


class ChangeType(str, Enum):
    """Type of ontology change proposed."""
    NEW_ENTITY_TYPE = "NEW_ENTITY_TYPE"
    NEW_RELATIONSHIP_TYPE = "NEW_RELATIONSHIP_TYPE"
    MODIFY_ENTITY_PROPERTIES = "MODIFY_ENTITY_PROPERTIES"
    MODIFY_RELATIONSHIP_PROPERTIES = "MODIFY_RELATIONSHIP_PROPERTIES"
    FLAG_INCONSISTENCY = "FLAG_INCONSISTENCY"
    SUGGEST_CONSTRAINT = "SUGGEST_CONSTRAINT"
    SUGGEST_INDEX = "SUGGEST_INDEX"
    DEPRECATE_ENTITY = "DEPRECATE_ENTITY"
    DEPRECATE_RELATIONSHIP = "DEPRECATE_RELATIONSHIP"
    MERGE_ENTITIES = "MERGE_ENTITIES"


class Severity(str, Enum):
    """Severity/urgency of the proposal."""
    CRITICAL = "CRITICAL"  # Data quality issue, immediate action needed
    HIGH = "HIGH"          # Important pattern, should review soon
    MEDIUM = "MEDIUM"      # Interesting pattern, review when convenient
    LOW = "LOW"            # Nice-to-have suggestion


class Evidence(BaseModel):
    """Evidence supporting a change proposal."""

    example_id: str = Field(
        ...,
        description="ID of example entity/relationship from Neo4j"
    )

    example_type: str = Field(
        ...,
        description="Type of example: 'NODE', 'RELATIONSHIP', 'PATTERN'"
    )

    properties: Optional[Dict[str, Any]] = Field(
        None,
        description="Relevant properties of the example"
    )

    context: Optional[str] = Field(
        None,
        description="Contextual explanation of why this is evidence"
    )

    frequency: Optional[int] = Field(
        None,
        description="How many times this pattern occurs in the graph"
    )


class ImpactAnalysis(BaseModel):
    """Analysis of potential impact of implementing this change."""

    affected_entities_count: Optional[int] = Field(
        None,
        description="Number of existing entities affected by this change"
    )

    affected_relationships_count: Optional[int] = Field(
        None,
        description="Number of existing relationships affected"
    )

    breaking_change: bool = Field(
        default=False,
        description="Whether this is a breaking change requiring migration"
    )

    migration_complexity: str = Field(
        default="LOW",
        description="Migration complexity: 'LOW', 'MEDIUM', 'HIGH'"
    )

    estimated_effort_hours: Optional[float] = Field(
        None,
        description="Estimated implementation effort in hours"
    )

    benefits: List[str] = Field(
        default_factory=list,
        description="Expected benefits of implementing this change"
    )

    risks: List[str] = Field(
        default_factory=list,
        description="Potential risks or downsides"
    )


class OntologyChangeProposal(BaseModel):
    """
    A proposed change to the ontology, generated by the OSS.

    All proposals require human review and approval before implementation.
    """

    # Identification
    proposal_id: str = Field(
        ...,
        description="Unique proposal ID. Format: OSS_YYYYMMDD_HHMMSS_UUID"
    )

    change_type: ChangeType = Field(
        ...,
        description="Type of change being proposed"
    )

    severity: Severity = Field(
        ...,
        description="Severity/urgency of this proposal"
    )

    # Proposal details
    title: str = Field(
        ...,
        description="Short, descriptive title"
    )

    description: str = Field(
        ...,
        description="Detailed explanation of what is being proposed and why"
    )

    definition: Optional[str] = Field(
        None,
        description="Proposed schema definition (Pydantic model, Cypher constraint, etc.)"
    )

    # Evidence
    evidence: List[Evidence] = Field(
        default_factory=list,
        description="Examples from the graph database supporting this proposal"
    )

    pattern_query: Optional[str] = Field(
        None,
        description="Cypher query that identified this pattern"
    )

    occurrence_count: Optional[int] = Field(
        None,
        description="How many times this pattern occurs in current data"
    )

    # Confidence & validation
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="OSS confidence in this proposal (0.0-1.0)"
    )

    confidence_factors: Optional[Dict[str, float]] = Field(
        None,
        description="Breakdown of confidence calculation"
    )

    validation_checks: Optional[List[str]] = Field(
        None,
        description="Validation checks performed"
    )

    # Impact analysis
    impact_analysis: ImpactAnalysis = Field(
        ...,
        description="Analysis of potential impact of this change"
    )

    # Metadata
    oss_version: str = Field(
        default="1.0.0",
        description="Version of OSS that generated this proposal"
    )

    related_proposals: Optional[List[str]] = Field(
        None,
        description="IDs of related proposals"
    )

    tags: Optional[List[str]] = Field(
        None,
        description="Tags for categorization"
    )


class AnalysisResult(BaseModel):
    """Result of an OSS analysis cycle."""

    cycle_id: str = Field(..., description="Unique ID for this analysis cycle")
    started_at: datetime = Field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None

    patterns_detected: int = Field(default=0)
    inconsistencies_detected: int = Field(default=0)
    proposals_generated: int = Field(default=0)
    duplicates_skipped: int = Field(
        default=0,
        description="Number of duplicate proposals skipped (Issue #4)"
    )
    proposals_submitted: int = Field(default=0)

    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)

    proposals: List[OntologyChangeProposal] = Field(default_factory=list)
