-- OSS Ontology Proposals Table
-- Stores change proposals generated by the Ontology Suggestion Service
-- Created: 2025-11-10

CREATE TABLE IF NOT EXISTS ontology_proposals (
    -- Primary identification
    id SERIAL PRIMARY KEY,
    proposal_id VARCHAR(100) UNIQUE NOT NULL,

    -- Classification
    change_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,

    -- Proposal details
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    definition TEXT,

    -- Evidence (JSON)
    evidence JSONB DEFAULT '[]'::jsonb,
    pattern_query TEXT,
    occurrence_count INTEGER,

    -- Confidence
    confidence FLOAT NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
    confidence_factors JSONB,
    validation_checks JSONB,

    -- Impact analysis (JSON)
    impact_analysis JSONB NOT NULL,

    -- Workflow status
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by VARCHAR(100),
    rejection_reason TEXT,
    implemented_at TIMESTAMP WITH TIME ZONE,

    -- Metadata
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_proposals_status ON ontology_proposals(status);
CREATE INDEX IF NOT EXISTS idx_proposals_severity ON ontology_proposals(severity);
CREATE INDEX IF NOT EXISTS idx_proposals_change_type ON ontology_proposals(change_type);
CREATE INDEX IF NOT EXISTS idx_proposals_created_at ON ontology_proposals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_proposals_confidence ON ontology_proposals(confidence DESC);

-- GIN index for JSONB columns (efficient JSON queries)
CREATE INDEX IF NOT EXISTS idx_proposals_evidence ON ontology_proposals USING GIN (evidence);
CREATE INDEX IF NOT EXISTS idx_proposals_impact ON ontology_proposals USING GIN (impact_analysis);

-- Comments for documentation
COMMENT ON TABLE ontology_proposals IS 'Ontology change proposals from OSS requiring human review';
COMMENT ON COLUMN ontology_proposals.proposal_id IS 'Unique ID format: OSS_YYYYMMDD_HHMMSS_UUID';
COMMENT ON COLUMN ontology_proposals.change_type IS 'Type: NEW_ENTITY_TYPE, MODIFY_ENTITY_PROPERTIES, FLAG_INCONSISTENCY, etc.';
COMMENT ON COLUMN ontology_proposals.severity IS 'Urgency: CRITICAL, HIGH, MEDIUM, LOW';
COMMENT ON COLUMN ontology_proposals.confidence IS 'OSS confidence in proposal (0.0-1.0)';
COMMENT ON COLUMN ontology_proposals.evidence IS 'JSON array of Evidence objects from Neo4j';
COMMENT ON COLUMN ontology_proposals.impact_analysis IS 'JSON object with ImpactAnalysis details';
COMMENT ON COLUMN ontology_proposals.status IS 'PENDING, UNDER_REVIEW, ACCEPTED, REJECTED, IMPLEMENTED';

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_ontology_proposals_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_ontology_proposals_updated_at
BEFORE UPDATE ON ontology_proposals
FOR EACH ROW
EXECUTE FUNCTION update_ontology_proposals_updated_at();
