"""add_legacy_feed_and_article_id_fields

Revision ID: 05b988c45bf9
Revises: 
Create Date: 2025-10-18 10:48:31.436967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05b988c45bf9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - MANUALLY ADJUSTED! ###
    # Only create research service tables, don't touch other services' tables
    op.create_table('research_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('depth', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_cache_cache_key'), 'research_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_research_cache_expires_at'), 'research_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_research_cache_id'), 'research_cache', ['id'], unique=False)
    op.create_table('research_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_template', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('default_model', sa.String(length=50), nullable=True),
    sa.Column('default_depth', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_templates_id'), 'research_templates', ['id'], unique=False)
    op.create_index('ix_research_templates_user_active', 'research_templates', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_research_templates_user_id'), 'research_templates', ['user_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('depth', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tasks_created', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_failed', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('results_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['research_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_runs_completed', 'research_runs', ['completed_at'], unique=False)
    op.create_index('ix_research_runs_created', 'research_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_id'), 'research_runs', ['id'], unique=False)
    op.create_index('ix_research_runs_scheduled', 'research_runs', ['scheduled_at', 'status'], unique=False)
    op.create_index(op.f('ix_research_runs_scheduled_at'), 'research_runs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_index(op.f('ix_research_runs_template_id'), 'research_runs', ['template_id'], unique=False)
    op.create_index('ix_research_runs_template_status', 'research_runs', ['template_id', 'status'], unique=False)
    op.create_index(op.f('ix_research_runs_user_id'), 'research_runs', ['user_id'], unique=False)
    op.create_index('ix_research_runs_user_status', 'research_runs', ['user_id', 'status'], unique=False)
    op.create_table('research_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('depth', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('feed_id', sa.UUID(), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('legacy_feed_id', sa.Integer(), nullable=True),
    sa.Column('legacy_article_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_article_id'), 'research_tasks', ['article_id'], unique=False)
    op.create_index('ix_research_tasks_created', 'research_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_tasks_feed_id'), 'research_tasks', ['feed_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_id'), 'research_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_research_tasks_legacy_article_id'), 'research_tasks', ['legacy_article_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_legacy_feed_id'), 'research_tasks', ['legacy_feed_id'], unique=False)
    op.create_index('ix_research_tasks_run_id', 'research_tasks', ['run_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_status'), 'research_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_research_tasks_user_id'), 'research_tasks', ['user_id'], unique=False)
    op.create_index('ix_research_tasks_user_status', 'research_tasks', ['user_id', 'status'], unique=False)
    op.create_table('cost_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_tracking_date'), 'cost_tracking', ['date'], unique=False)
    op.create_index(op.f('ix_cost_tracking_id'), 'cost_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_cost_tracking_user_id'), 'cost_tracking', ['user_id'], unique=False)

    # Note: All DROP statements removed to prevent deleting other services' tables
    # This service only manages research_* tables
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - MANUALLY ADJUSTED\! ###
    # Downgrade: Drop research service tables
    op.drop_table('cost_tracking')
    op.drop_table('research_tasks')
    op.drop_table('research_runs')
    op.drop_table('research_templates')
    op.drop_table('research_cache')
    # ### end Alembic commands ###
