"""SQLAlchemy model for ontology proposals."""
from sqlalchemy import Column, Integer, String, Text, Boolean, TIMESTAMP, Numeric
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func
from app.database import Base


class OntologyProposal(Base):
    """
    Ontology Proposal Model.

    Stores change proposals for the knowledge graph ontology,
    generated by the OSS (Ontology Suggestion System).
    """
    __tablename__ = "ontology_proposals"

    id = Column(Integer, primary_key=True, index=True)
    proposal_id = Column(String(100), unique=True, nullable=False, index=True)
    change_type = Column(String(50), nullable=False, index=True)
    severity = Column(String(20), nullable=False, index=True)
    title = Column(String(500), nullable=False)
    description = Column(Text)
    definition = Column(Text)
    evidence = Column(JSONB)
    pattern_query = Column(Text)
    occurrence_count = Column(Integer)
    confidence = Column(Numeric(5, 2))
    confidence_factors = Column(JSONB)
    validation_checks = Column(JSONB)
    impact_analysis = Column(JSONB)
    status = Column(String(50), default="PENDING", index=True)
    created_at = Column(TIMESTAMP(timezone=True), server_default=func.now(), nullable=False)
    reviewed_at = Column(TIMESTAMP(timezone=True))
    reviewed_by = Column(String(100))
    rejection_reason = Column(Text)
    implemented_at = Column(TIMESTAMP(timezone=True))
    updated_at = Column(TIMESTAMP(timezone=True), server_default=func.now())

    def __repr__(self):
        return f"<OntologyProposal {self.proposal_id}: {self.title}>"
