"""
Metric 2: Diagnosis Quality (Uncertainty Factor Accuracy)

Measures how accurately DIA identifies WHY the analysis is uncertain.

Success Criteria:
- Factor match score > 0.70
- Root cause identified: True
- Actionability score > 0.60
"""

from typing import List, Dict, Optional


def calculate_diagnosis_quality(
    predicted_factors: List[str],
    expected_factors: List[str],
    challenge_description: str,
    verification_plan: Optional[Dict] = None
) -> Dict[str, float]:
    """
    Measure quality of uncertainty diagnosis.

    Args:
        predicted_factors: Uncertainty factors generated by system
        expected_factors: Expected factors from ground truth
        challenge_description: Description of the challenge (for root cause check)
        verification_plan: Optional verification plan for context

    Returns:
        {
            "factor_match_score": float,        # Semantic similarity of factors
            "root_cause_identified": bool,      # Did it find the main issue?
            "actionability_score": float,       # Are factors actionable?
            "coverage_score": float             # How comprehensive?
        }
    """
    # ========================================================================
    # 1. Factor Match Score (Semantic Similarity)
    # ========================================================================
    factor_match_score = calculate_semantic_similarity(
        predicted_factors,
        expected_factors
    )

    # ========================================================================
    # 2. Root Cause Identification
    # ========================================================================
    root_cause_identified = check_root_cause(
        predicted_factors,
        challenge_description
    )

    # ========================================================================
    # 3. Actionability Score
    # ========================================================================
    actionability_score = calculate_actionability(predicted_factors)

    # ========================================================================
    # 4. Coverage Score
    # ========================================================================
    # How many key aspects are covered?
    coverage_score = calculate_coverage(predicted_factors, expected_factors)

    return {
        "factor_match_score": factor_match_score,
        "root_cause_identified": root_cause_identified,
        "actionability_score": actionability_score,
        "coverage_score": coverage_score
    }


def calculate_semantic_similarity(
    predicted: List[str],
    expected: List[str]
) -> float:
    """
    Calculate semantic similarity between factor lists using embeddings.

    For now, uses simple keyword overlap. TODO: Implement sentence-transformers.

    Args:
        predicted: Predicted uncertainty factors
        expected: Expected uncertainty factors

    Returns:
        Similarity score [0.0, 1.0]
    """
    if not predicted or not expected:
        return 0.0 if predicted != expected else 1.0

    # Simple keyword-based similarity for now
    # Extract keywords from both lists
    predicted_keywords = extract_keywords(predicted)
    expected_keywords = extract_keywords(expected)

    if not expected_keywords:
        return 0.0

    # Jaccard similarity
    intersection = predicted_keywords.intersection(expected_keywords)
    union = predicted_keywords.union(expected_keywords)

    if not union:
        return 0.0

    return len(intersection) / len(union)


def extract_keywords(factors: List[str]) -> set:
    """
    Extract important keywords from uncertainty factors.

    Removes stopwords and extracts meaningful terms.
    """
    import re

    # Common stopwords
    stopwords = {
        'a', 'an', 'the', 'in', 'on', 'at', 'to', 'for', 'of', 'with',
        'by', 'from', 'up', 'about', 'into', 'through', 'during', 'is',
        'are', 'was', 'were', 'been', 'be', 'have', 'has', 'had', 'do',
        'does', 'did', 'will', 'would', 'should', 'could', 'may', 'might',
        'must', 'can', 'this', 'that', 'these', 'those', 'and', 'or', 'but'
    }

    keywords = set()

    for factor in factors:
        # Lowercase and tokenize
        words = re.findall(r'\b\w+\b', factor.lower())

        # Filter stopwords
        for word in words:
            if word not in stopwords and len(word) > 2:
                keywords.add(word)

    return keywords


def check_root_cause(factors: List[str], challenge_description: str) -> bool:
    """
    Check if the root cause was identified.

    Looks for key terms from challenge description in uncertainty factors.

    Args:
        factors: Predicted uncertainty factors
        challenge_description: Ground truth challenge description

    Returns:
        True if root cause appears to be identified
    """
    if not factors or not challenge_description:
        return False

    # Extract key terms from challenge description
    challenge_keywords = extract_keywords([challenge_description])

    # Extract keywords from factors
    factor_keywords = extract_keywords(factors)

    # Check overlap (at least 30% of challenge keywords mentioned)
    if not challenge_keywords:
        return False

    overlap = len(challenge_keywords.intersection(factor_keywords))
    return (overlap / len(challenge_keywords)) >= 0.3


def calculate_actionability(factors: List[str]) -> float:
    """
    Calculate actionability score of uncertainty factors.

    Actionable factors suggest concrete verification steps.

    Args:
        factors: Uncertainty factors

    Returns:
        Actionability score [0.0, 1.0]
    """
    if not factors:
        return 0.0

    # Keywords indicating actionable factors
    actionable_keywords = [
        'verify', 'check', 'cross-reference', 'validate', 'review',
        'inconsistent', 'conflicting', 'missing', 'ambiguous',
        'unclear', 'contradictory', 'low-confidence', 'uncertain',
        'requires', 'needs', 'should', 'must', 'confirm'
    ]

    actionable_count = 0

    for factor in factors:
        factor_lower = factor.lower()
        if any(keyword in factor_lower for keyword in actionable_keywords):
            actionable_count += 1

    return actionable_count / len(factors)


def calculate_coverage(predicted: List[str], expected: List[str]) -> float:
    """
    Calculate how comprehensive the diagnosis is.

    Measures if all key aspects are covered.

    Args:
        predicted: Predicted factors
        expected: Expected factors

    Returns:
        Coverage score [0.0, 1.0]
    """
    if not expected:
        return 1.0 if not predicted else 0.0

    if not predicted:
        return 0.0

    # Count how many expected factors have some overlap with predicted
    expected_keywords = [extract_keywords([f]) for f in expected]
    predicted_keywords = extract_keywords(predicted)

    covered_count = 0

    for exp_kw in expected_keywords:
        if exp_kw.intersection(predicted_keywords):
            covered_count += 1

    return covered_count / len(expected_keywords)


def calculate_aggregate_diagnosis_quality(results: List[Dict[str, float]]) -> Dict[str, float]:
    """
    Aggregate diagnosis quality metrics across test cases.

    Args:
        results: List of diagnosis quality results

    Returns:
        Aggregated metrics
    """
    if not results:
        return {}

    import statistics

    metrics = {
        "factor_match_score": [],
        "root_cause_identified": [],
        "actionability_score": [],
        "coverage_score": []
    }

    for result in results:
        for key in metrics.keys():
            metrics[key].append(result[key])

    aggregated = {}
    for key, values in metrics.items():
        if key == "root_cause_identified":
            # Boolean: calculate rate
            aggregated[f"{key}_rate"] = sum(values) / len(values)
        else:
            aggregated[f"{key}_mean"] = statistics.mean(values)
            if len(values) > 1:
                aggregated[f"{key}_std"] = statistics.stdev(values)
            else:
                aggregated[f"{key}_std"] = 0.0

    return aggregated


def evaluate_diagnosis_quality(aggregated: Dict[str, float]) -> Dict[str, bool]:
    """
    Evaluate if diagnosis quality meets success criteria.

    Success Criteria:
    - Factor match score > 0.70
    - Root cause identified rate > 0.80
    - Actionability score > 0.60

    Args:
        aggregated: Output from calculate_aggregate_diagnosis_quality()

    Returns:
        Pass/fail for each criterion
    """
    results = {
        "factor_match_score_pass": aggregated.get("factor_match_score_mean", 0.0) > 0.70,
        "root_cause_identified_pass": aggregated.get("root_cause_identified_rate", 0.0) > 0.80,
        "actionability_score_pass": aggregated.get("actionability_score_mean", 0.0) > 0.60
    }

    results["overall_pass"] = all(results.values())

    return results
