"""
Metric 3: Planning Effectiveness (Verification Workflow Quality)

Measures how effectively DIA generates verification plans.

Success Criteria:
- Method coverage > 0.80
- Source coverage > 0.70
- Priority accuracy > 0.80
- Completeness score > 0.75
"""

from typing import List, Dict, Optional


def calculate_planning_effectiveness(
    predicted_plan: Dict,
    expected_plan: Dict
) -> Dict[str, float]:
    """
    Evaluate quality of verification plan.

    Args:
        predicted_plan: Verification plan generated by system
            {
                "priority": "high",
                "verification_methods": [...],
                "external_sources": [...],
                "expected_corrections": [...]
            }
        expected_plan: Ideal verification plan from ground truth

    Returns:
        {
            "method_coverage": float,           # % of ideal methods included
            "source_coverage": float,           # % of ideal sources included
            "priority_accuracy": float,         # Correct priority level?
            "efficiency_score": float,          # Not over-engineering?
            "completeness_score": float         # All necessary steps?
        }
    """
    # ========================================================================
    # 1. Method Coverage
    # ========================================================================
    method_coverage = calculate_set_coverage(
        predicted_plan.get("verification_methods", []),
        expected_plan.get("verification_methods", [])
    )

    # ========================================================================
    # 2. Source Coverage
    # ========================================================================
    source_coverage = calculate_set_coverage(
        predicted_plan.get("external_sources", []),
        expected_plan.get("external_sources", [])
    )

    # ========================================================================
    # 3. Priority Accuracy
    # ========================================================================
    priority_accuracy = calculate_priority_accuracy(
        predicted_plan.get("priority", "medium"),
        expected_plan.get("priority", "medium")
    )

    # ========================================================================
    # 4. Efficiency Score
    # ========================================================================
    efficiency_score = calculate_efficiency(
        predicted_plan.get("verification_methods", []),
        predicted_plan.get("external_sources", []),
        expected_plan.get("verification_methods", []),
        expected_plan.get("external_sources", [])
    )

    # ========================================================================
    # 5. Completeness Score
    # ========================================================================
    completeness_score = (method_coverage + source_coverage) / 2

    return {
        "method_coverage": method_coverage,
        "source_coverage": source_coverage,
        "priority_accuracy": priority_accuracy,
        "efficiency_score": efficiency_score,
        "completeness_score": completeness_score
    }


def calculate_set_coverage(
    predicted: List[str],
    expected: List[str]
) -> float:
    """
    Calculate coverage of expected items in predicted set.

    Uses semantic matching (normalized strings).

    Args:
        predicted: Predicted methods/sources
        expected: Expected methods/sources

    Returns:
        Coverage score [0.0, 1.0]
    """
    if not expected:
        return 1.0 if not predicted else 0.5

    if not predicted:
        return 0.0

    # Normalize strings for comparison
    predicted_norm = {normalize_string(p) for p in predicted}
    expected_norm = {normalize_string(e) for e in expected}

    # Calculate exact matches
    exact_matches = expected_norm.intersection(predicted_norm)

    # Calculate semantic matches for non-exact
    remaining_expected = expected_norm - exact_matches
    remaining_predicted = predicted_norm - exact_matches

    semantic_matches = count_semantic_matches(
        list(remaining_predicted),
        list(remaining_expected)
    )

    total_matches = len(exact_matches) + semantic_matches

    return total_matches / len(expected_norm)


def normalize_string(s: str) -> str:
    """Normalize string for comparison."""
    import re
    # Lowercase, remove extra whitespace, remove punctuation
    s = s.lower().strip()
    s = re.sub(r'[^\w\s-]', '', s)
    s = re.sub(r'\s+', ' ', s)
    return s


def count_semantic_matches(predicted: List[str], expected: List[str]) -> int:
    """
    Count semantic matches between two lists.

    Uses keyword overlap to determine if items are semantically similar.

    Args:
        predicted: Predicted items (normalized)
        expected: Expected items (normalized)

    Returns:
        Number of semantic matches
    """
    if not predicted or not expected:
        return 0

    matches = 0

    for exp in expected:
        exp_words = set(exp.split())

        for pred in predicted:
            pred_words = set(pred.split())

            # Calculate word overlap
            if exp_words and pred_words:
                overlap = len(exp_words.intersection(pred_words))
                overlap_ratio = overlap / len(exp_words)

                # Consider it a match if > 50% words overlap
                if overlap_ratio > 0.5:
                    matches += 1
                    break

    return matches


def calculate_priority_accuracy(
    predicted_priority: str,
    expected_priority: str
) -> float:
    """
    Calculate priority accuracy.

    Exact match = 1.0, ±1 level = 0.5, else 0.0

    Args:
        predicted_priority: Predicted priority level
        expected_priority: Expected priority level

    Returns:
        Accuracy score [0.0, 1.0]
    """
    priority_map = {
        "low": 1,
        "medium": 2,
        "high": 3,
        "critical": 4
    }

    expected_level = priority_map.get(expected_priority.lower(), 2)
    predicted_level = priority_map.get(predicted_priority.lower(), 2)

    distance = abs(expected_level - predicted_level)

    if distance == 0:
        return 1.0
    elif distance == 1:
        return 0.5
    else:
        return 0.0


def calculate_efficiency(
    predicted_methods: List[str],
    predicted_sources: List[str],
    expected_methods: List[str],
    expected_sources: List[str]
) -> float:
    """
    Calculate efficiency score.

    Penalizes over-engineering (too many steps).

    Args:
        predicted_methods: Predicted verification methods
        predicted_sources: Predicted external sources
        expected_methods: Expected verification methods
        expected_sources: Expected external sources

    Returns:
        Efficiency score [0.0, 1.0]
    """
    predicted_steps = len(predicted_methods) + len(predicted_sources)
    expected_steps = len(expected_methods) + len(expected_sources)

    if expected_steps == 0:
        return 1.0 if predicted_steps == 0 else 0.0

    if predicted_steps <= expected_steps:
        # Not over-engineering
        return 1.0
    else:
        # Penalty for excess steps (10% per extra step)
        excess = predicted_steps - expected_steps
        return max(0.0, 1.0 - (excess * 0.1))


def calculate_aggregate_planning_effectiveness(
    results: List[Dict[str, float]]
) -> Dict[str, float]:
    """
    Aggregate planning effectiveness metrics across test cases.

    Args:
        results: List of planning effectiveness results

    Returns:
        Aggregated metrics
    """
    if not results:
        return {}

    import statistics

    metrics = {
        "method_coverage": [],
        "source_coverage": [],
        "priority_accuracy": [],
        "efficiency_score": [],
        "completeness_score": []
    }

    for result in results:
        for key in metrics.keys():
            metrics[key].append(result[key])

    aggregated = {}
    for key, values in metrics.items():
        aggregated[f"{key}_mean"] = statistics.mean(values)
        if len(values) > 1:
            aggregated[f"{key}_std"] = statistics.stdev(values)
        else:
            aggregated[f"{key}_std"] = 0.0

    return aggregated


def evaluate_planning_effectiveness(aggregated: Dict[str, float]) -> Dict[str, bool]:
    """
    Evaluate if planning effectiveness meets success criteria.

    Success Criteria:
    - Method coverage > 0.80
    - Source coverage > 0.70
    - Priority accuracy > 0.80
    - Completeness score > 0.75

    Args:
        aggregated: Output from calculate_aggregate_planning_effectiveness()

    Returns:
        Pass/fail for each criterion
    """
    results = {
        "method_coverage_pass": aggregated.get("method_coverage_mean", 0.0) > 0.80,
        "source_coverage_pass": aggregated.get("source_coverage_mean", 0.0) > 0.70,
        "priority_accuracy_pass": aggregated.get("priority_accuracy_mean", 0.0) > 0.80,
        "completeness_score_pass": aggregated.get("completeness_score_mean", 0.0) > 0.75
    }

    results["overall_pass"] = all(results.values())

    return results
